language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "stable"
env:
  global:
  - COVERALLS_PARALLEL=true
  jobs:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
cache: npm
before_script:
- npm install -g npm-install-peers
- npm-install-peers
script:
- npm run test:$TEST_SUITE
after_success:
- ./coveralls_upload.sh
jobs:
  exclude:
    - node_js: "8"
      env: TEST_SUITE=lint
    - node_js: "8"
      env: TEST_SUITE=docs
    - node_js: "8"
      env: TEST_SUITE=build
    - node_js: "9"
      env: TEST_SUITE=lint
    - node_js: "9"
      env: TEST_SUITE=docs
    - node_js: "9"
      env: TEST_SUITE=build
    - node_js: "10"
      env: TEST_SUITE=lint
    - node_js: "10"
      env: TEST_SUITE=docs
    - node_js: "10"
      env: TEST_SUITE=build
  include:
  - stage: npm release
    node_js: 'stable'
    script: npm run build
    if: tag IS present
    deploy:
      provider: npm
      edge: true
      cleanup: false
      email: $npm_email
      api_token: $npm_api_key
      on:
        tags: true
        repo: donmahallem/TrapezeApiClientCacheNode
  - stage: github pages release
    node_js: 'stable'
    script: npm run docs
    if: branch = master
    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: docs
      token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      on:
notifications:
  webhooks: https://coveralls.io/webhook